ignore = ["lib"]

# Forces usage of tabs for indentation
hard_tabs = true
edition = "2024"
newline_style = "Unix" # \n
use_field_init_shorthand = true # {x: x, y: y, z: z} -> {x, y, z}
use_try_shorthand = true # try!(...) -> ...?
# Unstable Below
unstable_features = true
format_code_in_doc_comments = true
imports_granularity = "Crate"
normalize_comments = true # /* ... */ -> // ...
normalize_doc_attributes = true # #[doc(...)] -> /// ...
group_imports = "StdExternalCrate" # Preferred import grouping and ordering
