use inputbot::KeybdKey;

pub const KEY_PRESSED_LIT_DELAY: std::time::Duration = std::time::Duration::from_millis(250);

pub const KEY_PRESSED_CLEANUP_DELAY: std::time::Duration = std::time::Duration::from_millis(33);

pub struct VisualKeybdKeyHolder {
    pub size: f32,
    pub key: KeybdKey,
    pub name: &'static str,
    pub column: u32,
}

pub const KEYS: [&[VisualKeybdKeyHolder]; 6] = [
    &ROW_ONE, &ROW_TWO, &ROW_THREE, &ROW_FOUR, &ROW_FIVE, &ROW_SIX,
];

const ROW_ONE: [VisualKeybdKeyHolder; 21] = [
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::EscapeKey,
        name: "Esc",
        column: 0,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::OtherKey(u64::MAX - 1),
        name: " ",
        column: 1,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::F1Key,
        name: "F1",
        column: 2,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::F2Key,
        name: "F2",
        column: 3,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::F3Key,
        name: "F3",
        column: 4,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::F4Key,
        name: "F4",
        column: 5,
    },
    VisualKeybdKeyHolder {
        size: 0.5,
        key: KeybdKey::OtherKey(u64::MAX - 1),
        name: " ",
        column: 6,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::F5Key,
        name: "F5",
        column: 7,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::F6Key,
        name: "F6",
        column: 8,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::F7Key,
        name: "F7",
        column: 9,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::F8Key,
        name: "F8",
        column: 10,
    },
    VisualKeybdKeyHolder {
        size: 0.5,
        key: KeybdKey::OtherKey(u64::MAX - 1),
        name: " ",
        column: 11,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::F9Key,
        name: "F9",
        column: 12,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::F10Key,
        name: "F10",
        column: 13,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::F11Key,
        name: "F11",
        column: 14,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::F12Key,
        name: "F12",
        column: 15,
    },
    VisualKeybdKeyHolder {
        size: 0.5,
        key: KeybdKey::OtherKey(u64::MAX - 1),
        name: " ",
        column: 16,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::OtherKey(u64::MAX - 1 - 1),
        name: "Prt.Scn",
        column: 17,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::OtherKey(u64::MAX - 1 - 1),
        name: "Pause",
        column: 18,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::ScrollLockKey,
        name: "Scrl.Lock",
        column: 19,
    },
    VisualKeybdKeyHolder {
        size: 4.5,
        key: KeybdKey::OtherKey(u64::MAX - 1),
        name: " ",
        column: 20,
    },
];
const ROW_TWO: [VisualKeybdKeyHolder; 23] = [
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::BackquoteKey,
        name: "`",
        column: 0,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::Numrow1Key,
        name: "1",
        column: 1,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::Numrow2Key,
        name: "2",
        column: 2,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::Numrow3Key,
        name: "3",
        column: 3,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::Numrow4Key,
        name: "4",
        column: 4,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::Numrow5Key,
        name: "5",
        column: 5,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::Numrow6Key,
        name: "6",
        column: 6,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::Numrow7Key,
        name: "7",
        column: 7,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::Numrow8Key,
        name: "8",
        column: 8,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::Numrow9Key,
        name: "9",
        column: 9,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::Numrow0Key,
        name: "0",
        column: 10,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::MinusKey,
        name: "-",
        column: 11,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::EqualKey,
        name: "=",
        column: 12,
    },
    VisualKeybdKeyHolder {
        size: 2.0,
        key: KeybdKey::BackspaceKey,
        name: "<--",
        column: 13,
    },
    VisualKeybdKeyHolder {
        size: 0.5,
        key: KeybdKey::OtherKey(u64::MAX - 1),
        name: " ",
        column: 14,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::InsertKey,
        name: "Ins",
        column: 15,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::HomeKey,
        name: "Home",
        column: 16,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::PageUpKey,
        name: "Pg.Up",
        column: 17,
    },
    VisualKeybdKeyHolder {
        size: 0.5,
        key: KeybdKey::OtherKey(u64::MAX - 1),
        name: " ",
        column: 18,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::NumLockKey,
        name: "NumLk",
        column: 19,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::OtherKey(61),
        name: "/",
        column: 20,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::OtherKey(63),
        name: "*",
        column: 21,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::OtherKey(109),
        name: "-",
        column: 22,
    },
];
const ROW_THREE: [VisualKeybdKeyHolder; 23] = [
    VisualKeybdKeyHolder {
        size: 1.5,
        key: KeybdKey::TabKey,
        name: "-->",
        column: 0,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::QKey,
        name: "Q",
        column: 1,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::WKey,
        name: "W",
        column: 2,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::EKey,
        name: "E",
        column: 3,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::RKey,
        name: "R",
        column: 4,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::TKey,
        name: "T",
        column: 5,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::YKey,
        name: "Y",
        column: 6,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::UKey,
        name: "U",
        column: 7,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::IKey,
        name: "I",
        column: 8,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::OKey,
        name: "O",
        column: 9,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::PKey,
        name: "P",
        column: 10,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::LBracketKey,
        name: "[",
        column: 11,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::RBracketKey,
        name: "]",
        column: 12,
    },
    VisualKeybdKeyHolder {
        size: 1.5,
        key: KeybdKey::BackslashKey,
        name: "\\",
        column: 13,
    },
    VisualKeybdKeyHolder {
        size: 0.5,
        key: KeybdKey::OtherKey(u64::MAX - 1),
        name: " ",
        column: 14,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::DeleteKey,
        name: "Del",
        column: 15,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::EndKey,
        name: "End",
        column: 16,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::PageDownKey,
        name: "Pg.Down",
        column: 17,
    },
    VisualKeybdKeyHolder {
        size: 0.5,
        key: KeybdKey::OtherKey(u64::MAX - 1),
        name: " ",
        column: 18,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::Numpad7Key,
        name: "7",
        column: 19,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::Numpad8Key,
        name: "8",
        column: 20,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::Numpad9Key,
        name: "9",
        column: 21,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::OtherKey(69),
        name: "+",
        column: 22,
    },
];
const ROW_FOUR: [VisualKeybdKeyHolder; 18] = [
    VisualKeybdKeyHolder {
        size: 1.75,
        key: KeybdKey::CapsLockKey,
        name: "Caps",
        column: 0,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::AKey,
        name: "A",
        column: 1,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::SKey,
        name: "S",
        column: 2,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::DKey,
        name: "D",
        column: 3,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::FKey,
        name: "F",
        column: 4,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::GKey,
        name: "G",
        column: 5,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::HKey,
        name: "H",
        column: 6,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::JKey,
        name: "J",
        column: 7,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::KKey,
        name: "K",
        column: 8,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::LKey,
        name: "L",
        column: 9,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::SemicolonKey,
        name: ";",
        column: 10,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::QuoteKey,
        name: "'",
        column: 11,
    },
    VisualKeybdKeyHolder {
        size: 2.25,
        key: KeybdKey::EnterKey,
        name: "Enter",
        column: 12,
    },
    VisualKeybdKeyHolder {
        size: 4.0,
        key: KeybdKey::OtherKey(u64::MAX - 1),
        name: " ",
        column: 13,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::Numpad4Key,
        name: "4",
        column: 14,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::Numpad5Key,
        name: "5",
        column: 15,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::Numpad6Key,
        name: "6",
        column: 16,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::OtherKey(69),
        name: "+",
        column: 17,
    },
];
const ROW_FIVE: [VisualKeybdKeyHolder; 19] = [
    VisualKeybdKeyHolder {
        size: 2.5,
        key: KeybdKey::LShiftKey,
        name: "Shift",
        column: 0,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::ZKey,
        name: "Z",
        column: 1,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::XKey,
        name: "X",
        column: 2,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::CKey,
        name: "C",
        column: 3,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::VKey,
        name: "V",
        column: 4,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::BKey,
        name: "B",
        column: 5,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::NKey,
        name: "N",
        column: 6,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::MKey,
        name: "M",
        column: 7,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::CommaKey,
        name: ",",
        column: 8,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::PeriodKey,
        name: ".",
        column: 9,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::SlashKey,
        name: "/",
        column: 10,
    },
    VisualKeybdKeyHolder {
        size: 2.5,
        key: KeybdKey::RShiftKey,
        name: "Shift",
        column: 11,
    },
    VisualKeybdKeyHolder {
        size: 1.5,
        key: KeybdKey::OtherKey(u64::MAX - 1),
        name: " ",
        column: 12,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::UpKey,
        name: "^",
        column: 13,
    },
    VisualKeybdKeyHolder {
        size: 1.5,
        key: KeybdKey::OtherKey(u64::MAX - 1),
        name: " ",
        column: 14,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::Numpad1Key,
        name: "1",
        column: 15,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::Numpad2Key,
        name: "2",
        column: 16,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::Numpad3Key,
        name: "3",
        column: 17,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::OtherKey(96),
        name: "Enter",
        column: 18,
    },
];
const ROW_SIX: [VisualKeybdKeyHolder; 15] = [
    VisualKeybdKeyHolder {
        size: 1.5,
        key: KeybdKey::LControlKey,
        name: "Ctrl",
        column: 0,
    },
    VisualKeybdKeyHolder {
        size: 1.5,
        key: KeybdKey::LSuper,
        name: "Win",
        column: 1,
    },
    VisualKeybdKeyHolder {
        size: 1.5,
        key: KeybdKey::LAltKey,
        name: "Alt",
        column: 2,
    },
    VisualKeybdKeyHolder {
        size: 6.0,
        key: KeybdKey::SpaceKey,
        name: "----",
        column: 3,
    },
    VisualKeybdKeyHolder {
        size: 1.5,
        key: KeybdKey::RAltKey,
        name: "Alt",
        column: 4,
    },
    VisualKeybdKeyHolder {
        size: 1.5,
        key: KeybdKey::RSuper,
        name: "Win",
        column: 5,
    },
    VisualKeybdKeyHolder {
        size: 1.5,
        key: KeybdKey::RControlKey,
        name: "Ctrl",
        column: 6,
    },
    VisualKeybdKeyHolder {
        size: 0.5,
        key: KeybdKey::OtherKey(u64::MAX - 1),
        name: " ",
        column: 7,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::LeftKey,
        name: "<",
        column: 8,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::DownKey,
        name: "V",
        column: 9,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::RightKey,
        name: ">",
        column: 10,
    },
    VisualKeybdKeyHolder {
        size: 0.5,
        key: KeybdKey::OtherKey(u64::MAX - 1),
        name: " ",
        column: 11,
    },
    VisualKeybdKeyHolder {
        size: 2.0,
        key: KeybdKey::Numpad0Key,
        name: "0",
        column: 12,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::DeleteKey,
        name: ".",
        column: 13,
    },
    VisualKeybdKeyHolder {
        size: 1.0,
        key: KeybdKey::OtherKey(96),
        name: "Enter",
        column: 14,
    },
];
